### ISSUE TITLE
Incredible work

### ISSUE THREAD

**Issue by isaac-weisberg** [Flight-School/CodablePerformance#1]
Really enjoyed reading the article, and it's a great effort that you've put there. I was wondering, are you planning to extend the observation by testing datasets multiple times bigger, procedurally generating?

**Comment by mattt** [comment]
Hi @isaac-weisberg. Thanks for the kind words!

I don't currently have plans to expand on this project. However, I'd be interested to see more comprehensive benchmarking results if anyone else investigates this further.
